# ~/.config/sway/conf.d/appearance.conf

default_border pixel 2
default_floating_border pixel 2
hide_edge_borders smart



gaps inner 6
gaps outer 8


smart_gaps off

font pango:FiraCode Nerd Font 10
seat seat0 xcursor_theme Adwaita 20

set $gnome-schema org.gnome.desktop.interface
exec_always {
	Rgsettings set org.gnome.desktop.interface gtk-theme 'adw-gtk3-dark'
    gsettings set $gnome-schema icon-theme 'Reversal-dark'
    gsettings set $gnome-schema cursor-theme 'Adwaita'
    gsettings set $gnome-schema font-name 'FiraCode Nerd Font'
    gsettings set $gnome-schema color-scheme 'prefer-dark'
}

# --- Bordes y Esquinas ---
corner_radius 0
smart_corner_radius off

# --- Sombras ---
shadows enable
shadow_blur_radius 20
shadow_color #000000A0

# --- Efectos de Capa (Blur) ---
# Esto aplica blur a Waybar y Rofi si los usas
layer_effects "waybar" blur enable; shadows enable; corner_radius 10
layer_effects "rofi" blur enable; shadows enable; corner_radius 15

# --- Difuminado de Ventanas ---
blur enable
blur_passes 3
blur_radius 7

