# Definición de variables de color (Estética Teto)
set $teto_pink   #ff6699
set $teto_dark   #1a161d
set $teto_white  #fce1e4
set $teto_gray   #45475a

# Aplicar estos colores a las clases de ventanas de Sway
# class                 border       backgr.      text         indicator    child_border
client.focused          $teto_pink   $teto_dark   $teto_pink   $teto_pink   $teto_pink
client.focused_inactive $teto_gray   $teto_dark   $teto_gray   $teto_dark   $teto_dark
client.unfocused        $teto_dark   $teto_dark   $teto_gray   $teto_dark   $teto_dark
client.urgent           #eb4d4b      #eb4d4b      #ffffff      #eb4d4b      #eb4d4b

# Definimos el color principal
set $teto_magenta #ff6699

# Aplicamos el color a las ventanas activas para que el borde siempre sea visible
client.focused $teto_magenta $teto_magenta #ffffff $teto_magenta $teto_magenta
